session_name: local
shell_command_before:
  -  "source $HOME/dotfiles/_tmuxp/my_env_var.sh"
# before_script: "$HOME/dotfiles/_tmuxp/my_env_var.sh"
windows:
  - window_name: dotfiles
    window_index: 0
    focus: true
    layout: main-vertical
    panes:
    - shell_command:
      - 'cd $HOME/dotfiles/ && vim _vimrc'
      focus: true
    - shell_command:
      - 'cd $HOME/dotfiles'
      - "tmux resize-pane -t 2 -x $TMUX_WINDOW_WIDTH_ONE_THIRD"
  - window_name: golang
    window_index: 1
    # focus: true
    layout: main-vertical
    panes:
    - shell_command:
      - 'cd $HOME/.ghq/github.com/rainbow23/study_golang'
      - 'nvim sample.go'
    - shell_command:
      - 'cd $HOME/.ghq/github.com/rainbow23/study_golang'
      - "tmux resize-pane -t 2 -x $TMUX_WINDOW_WIDTH_ONE_THIRD"
      focus: true
