version: '3'
services:
  # base:
  #   build: ./docker/base
  #   image: rainbow23/base_dotfiles:latest
  #   container_name: rainbow23-dotfiles
  publish:
    build: .
    image: rainbow23/publish_dotfiles:latest
    container_name: rainbow23-publish-dotfiles
    volumes:
      - ${PWD}:/home/rainbow23/dotfiles
