version: '3'
services:
  # base:
  #   build: ./docker/base
  #   image: rainbow23/base_dotfiles:latest
  #   container_name: rainbow23-dotfiles
  test:
    build: .
    image: test_dotfiles:latest
    container_name: rainbow23-dotfiles-test
    volumes:
      - ${PWD}:/home/rainbow23/dotfiles
