#!/bin/zsh
export XDG_CONFIG_HOME=$HOME/.config
# -------------------------------------
# zshのオプション
# -------------------------------------
# コマンド履歴
HISTFILE=~/.zsh_history
HISTSIZE=6000000
SAVEHIST=6000000
setopt hist_ignore_dups # 直前と同じコマンドをヒストリに追加しない
setopt share_history    # 異なるウィンドウでコマンドヒストリを共有する
setopt hist_no_store    # historyコマンドは履歴に登録しない
setopt auto_menu        # タブで補完候補を表示する
setopt auto_list        # 補完候補が複数ある時に、一覧表示

## 入力しているコマンド名が間違っている場合にもしかして：を出す。
setopt correct
# ビープを鳴らさない
setopt no_beep
## 色を使う
setopt prompt_subst
## ^Dでログアウトしない。
setopt ignoreeof
## バックグラウンドジョブが終了したらすぐに知らせる。
setopt no_tify

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# -------------------------------------
# キーバインド vi mode
# -------------------------------------
bindkey -v
# mode change time to 0.1seconds
# export KEYTIMEOUT=1
# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select

function cdup() {
   echo
   cd ..
   zle reset-prompt
}
zle -N cdup
bindkey '^K' cdup
bindkey "^R" history-incremental-search-backward

# -------------------------------------
# その他
# -------------------------------------
# cdしたあとで、自動的に ls する
function chpwd() { ls -ltr }
# iTerm2のタブ名を変更する
function title {
    echo -ne "\033]0;"$*"\007"
}


# -------------------------------------
# source
# -------------------------------------
source $HOME/dotfiles/zsh/_zsh-my-theme.zsh
source $HOME/dotfiles/source.sh
source $HOME/dotfiles/etc/alias.sh
source $HOME/dotfiles/etc/fzf.sh
source $HOME/dotfiles/mru.sh
 # source $HOME/dotfiles/zsh/_zplugin.sh

## 補完機能の強化
autoload -Uz compinit && compinit -i
# 補完候補に色つける
autoload -U colors && colors
zstyle ':completion:*' list-colors "${LS_COLORS}"
# 大文字と小文字の区別なし
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' '+m:{A-Z}={a-z}'
zstyle ':completion:*:default' menu select=2
# kill コマンドのようなものに関しては候補をタブで選択できるようにする
zstyle ':completion:*:processes' menu yes select=2
